### ISSUE TITLE
Homebrew 

### ISSUE THREAD

**Issue by nysthee** [jckuester/awsweeper#26]
FYI I submitted a pr to get awsweeper into Homebrew: https://github.com/Homebrew/homebrew-core/pull/33984

**Comment by nysthee** [comment]
Unfortunately, they declined the PR. Maybe you could host the tap yourself? Then you could also use the bins directly instead of building it on install.

**Comment by jckuester** [comment]
Thanks :) Just 5 more stars to go and we can try again. I am also planning to implement new features to AWSweeper, which hopefully makes it more attractive. Just added a filter to filter by creation date and will do a `--all-region` flag soon to find resources in any region instead of just one.

**Comment by nysthee** [comment]
4 stars :)

**Comment by jckuester** [comment]
I guess, you can try again :) Please.

**Comment by nysthee** [comment]
Done: https://github.com/Homebrew/homebrew-core/pull/34429

Fingers crossed!

**Comment by Ilselott** [comment]
Hey, any news on the tap ? :)

**Comment by aghassemlouei** [comment]
Added a star and following up; anyone willing to try again?

**Comment by andreamaruccia** [comment]
> Thanks :) Just 5 more stars to go and we can try again. I am also planning to implement new features to AWSweeper, which hopefully makes it more attractive. Just added a filter to filter by creation date and will do a `--all-region` flag soon to find resources in any region instead of just one.

how do you star it?

**Comment by chenrui333** [comment]
I just filed a new PR to bring this utility tool to homebrew-core. :)

**Comment by chenrui333** [comment]
I just merged and install the formula, which works. Issue is good to be closed now. 🎉 
```
$ brew install awsweeper
==> Downloading https://homebrew.bintray.com/bottles/awsweeper-0.10.1.mojave.bottle.tar.gz
Already downloaded: ==> Downloading https://homebrew.bintray.com/bottles/awsweeper-0.10.1.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring awsweeper-0.10.1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/awsweeper/0.10.1: 5 files, 189.7MB
```

**Comment by jckuester** [comment]
Awesome, @chenrui333. That's very cool, thank you so much! I'll close this issue once I've added homebrew to the install section of the README.

**Comment by chenrui333** [comment]
Nice!

**Comment by jckuester** [comment]
@chenrui333, I just saw that you asked in the beginning of this thread

>  Maybe you could host the tap yourself?

Would hosting a third-party tap still make sense or doesn't it matter now where you added awsweeper to homebrew-core (which is very cool!). I am asking because I noticed the [hard-coded version v0.10.1](https://github.com/Homebrew/homebrew-core/pull/57503/files#diff-83a096bd66d444cd9eb2f13a355acb14R4) in the homebrew PR. Does it mean for every new release of awsweeper, a new PR must opened with the homebrew-core repo?

**Comment by chenrui333** [comment]
> @chenrui333, I just saw that you asked in the beginning of this thread
> 
> > Maybe you could host the tap yourself?
> 
> Would hosting a third-party tap still make sense or doesn't it matter now where you added awsweeper to homebrew-core (which is very cool!). I am asking because I noticed the [hard-coded version v0.10.1](https://github.com/Homebrew/homebrew-core/pull/57503/files#diff-83a096bd66d444cd9eb2f13a355acb14R4) in the homebrew PR. Does it mean for every new release of awsweeper, a new PR must opened with the homebrew-core repo?

Since this is already in the homebrew-core, it would be taken where there is new release. 

If there is any installation or test issue, we will open a new issue in here to discuss. 

With that being said, there is no reason to maintain a separate tap (even though technically you can do that.)

Let me know if this makes more sense. :)

**Comment by jckuester** [comment]
I understand, so new versions of awsweeper are automatically picked up by homebrew-core. Thanks again for adding brew support.

**Comment by chenrui333** [comment]
yeah, no problem, I might going to file another PR about setting up a new action of doing release automation for awsweeper tool :)
