### ISSUE TITLE
error: go get -u -v github.com/cloudetc/awsweeper

### ISSUE THREAD

**Issue by harkamals** [jckuester/awsweeper#29]
Hi - I am trying to get the project and try it out, but this error, please advise, thank you.

`github.com/aws/aws-sdk-go/service/ec2/ec2iface
github.com/cloudetc/awsweeper/resource
github.com/cloudetc/awsweeper/command
# github.com/cloudetc/awsweeper/command
go/src/github.com/cloudetc/awsweeper/command/wrapped_main.go:137:27: cannot use conf (type *"github.com/hashicorp/terraform/terraform".ResourceConfig) as type *"github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform".ResourceConfig in argument to p.Validate
go/src/github.com/cloudetc/awsweeper/command/wrapped_main.go:146:23: cannot use conf (type *"github.com/hashicorp/terraform/terraform".ResourceConfig) as type *"github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform".ResourceConfig in argument to p.Configure
go/src/github.com/cloudetc/awsweeper/command/wrapped_main.go:151:9: cannot use &p (type *"github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider) as type *"github.com/hashicorp/terraform/terraform".ResourceProvider in return argument:
	*"github.com/hashicorp/terraform/terraform".ResourceProvider is pointer to interface, not interface
`

**Comment by jckuester** [comment]
Thanks, I will look into it. If you want to try the tool, you can also use the binary (https://github.com/cloudetc/awsweeper/releases) for now, which is tested (https://gitlab.com/jckuester/awsweeper/pipelines) and should work.

**Comment by harkamals** [comment]
Thanks, I'm to join forces with you further development of this awesome tool.

So please help me move on this issue.

For now, I removed the vendor folder from terraform-provider-aws folder, this let me compile it.

**Comment by jckuester** [comment]
Please just `git clone` this repo, and not use `go get`. Best is to clone to a folder that is not in your gopath, as this project uses go modules. Then run `make build` as usual.

**Comment by harkamals** [comment]
thanks, works now :)
