### ISSUE TITLE
Delete Lambda functions

### ISSUE THREAD

**Issue by cloudlena** [jckuester/awsweeper#41]
It would be neat if the tool supported deleting `aws_lambda_function`s.

**Comment by aghassemlouei** [comment]
Bumping this request as well; would be beneficial to have!

**Comment by jckuester** [comment]
Hi @aghassemlouei again. Would you like to provide some initial PR for this? I can then do the rest.

**Comment by jckuester** [comment]
See https://github.com/cloudetc/awsweeper/pull/85; still need to implement tag support.

**Comment by jckuester** [comment]
Released in https://github.com/cloudetc/awsweeper/releases/tag/v0.7.0. FYI, I am working currently on a general solution to support tags for all resources.

**Comment by jckuester** [comment]
Tags for `aws_lambda_function` resources are finally working in the new release: https://github.com/cloudetc/awsweeper/releases/tag/v0.9.0
