### ISSUE TITLE
install.sh

### ISSUE THREAD

**Issue by sulaimanismail** [jckuester/awsweeper#88]
Hi,

some reason I'm not able to install on my Mac os is there any help or guide,

Thanks you in advance.

$ curl -sSfL https://raw.githubusercontent.com/cloudetc/awsweeper/master/install.sh | sh -s v0.5.0
cloudetc/awsweeper info checking GitHub for tag 'v0.5.0'
cloudetc/awsweeper info found version: 0.5.0 for v0.5.0/darwin/amd64
localuser@xxxxxxxxx ~/allstate_Devops/awsweeper (master)
$ awsweeper --help
bash: awsweeper: command not found

**Comment by jckuester** [comment]
Hi @sulaimanismail :wave: 

Definitely my fault, I made a mistake in the release config. I fixed it in https://github.com/cloudetc/awsweeper/releases/tag/v0.6.0, please try the new release. Thanks.

**Comment by andreamaruccia** [comment]
it works here now thank you!
