### ISSUE TITLE
aws_ebs_snapshot doesn't support import

### ISSUE THREAD

**Issue by zhaomengru2015** [jckuester/awsweeper#92]
delete aws_ecs_snapshot failed with the following error:
```shell
error=failed to import resource: resource aws_ebs_snapshot doesn't support import
```

**Comment by jckuester** [comment]
Hi @zhaomengru2015 :wave: 

Sorry for the bad experience and thanks for reporting the issue. I will have a look and try to come up with a fix.

**Comment by jckuester** [comment]
I came up with a fix https://github.com/cloudetc/awsweeper/pull/93 and will make a release tomorrow.

**Comment by jckuester** [comment]
Fixed in https://github.com/cloudetc/awsweeper/releases/tag/v0.7.0. Let me know if it works for you. Thanks.
